### ISSUE TITLE
Would it be possible to implement krb5?

### ISSUE THREAD

**Issue by nishitjpatel** [statusengine/interface#31]
I am looking to use kerberos for authentication.   looks like it is not currently possible with ldap.php.

**Comment by nook24** [comment]
I never used Kerberos but it should not be super hard to implement because the web server handles all the authentication part. Is this correct?
A quick Google search came up with `libapache2-mod-auth-kerb`

So basically you can use Kerberos out of the box by configure your apache to handle the authentication and enable anonymous access in Statusengine's config.
How ever this comes with the small disadvantaged that all external commands will show Anonymous as author.
<img width="515" alt="Bildschirmfoto 2019-10-24 um 20 42 00" src="https://user-images.githubusercontent.com/9019992/67515709-80a46080-f69f-11e9-8a8b-d9cb16bf71ad.png">

I will take a look at this over the weekend...

**Comment by nishitjpatel** [comment]
Thanks.   I am using mod_auth_kerb (redhat) for thruk/naemon and getting in as user identified in active directory.    i would like author to show as correct users not anonymous

**Comment by nook24** [comment]
Could you please post what's inside of the header `REMOTE_USER` ?
```php
<?php
echo $_SERVER['AUTH_TYPE'];
echo "<br/>";
echo $_SERVER['REMOTE_USER'];
echo "<br/>";
```

I don't have an AD at home :)

**Comment by nook24** [comment]
Please reopen this, if it's still a thing
