### ISSUE TITLE
Disregard ACK for block display

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#4]
Hi,

I find that it is not necessary to highlight a WARN / CRIT in the dashboard when it is ACK.

**Comment by nook24** [comment]
I am/was struggling with this as well...
But I thing it is wrong to remove services from the dashboard, just because they are acknowledged, because they are still broken...

This is why I added the "Detected issues" page and dashboard, because this only includes services that are not in downtime and not acknowledged...

So at the moment I have no idea, how to add this to the dashboard, or to the current boxes.

**Comment by nook24** [comment]
See linked issue #3
